(tests
 (names main sl_surface lan_surface lan_erase)
 (modules (:standard \ target_catalog lan_emit lan_recursive_emit lan_foreign_emit lan_async_emit lan_foreign_types_emit lan_models_emit lan_connections_emit))
 (libraries kanon_kernel kanon_surface))

(test
 (name target_catalog)
 (modules target_catalog)
 (libraries lanyard_target))

(test
 (name lan_emit)
 (modules lan_emit)
 (libraries kanon_kernel lanyard_rust))

(test
 (name lan_recursive_emit)
 (modules lan_recursive_emit)
 (libraries kanon_kernel lanyard_rust))

(test
 (name lan_foreign_emit)
 (modules lan_foreign_emit)
 (libraries kanon_kernel kanon_surface lanyard_rust lanyard_target))

(test
 (name lan_async_emit)
 (modules lan_async_emit)
 (libraries kanon_kernel kanon_surface lanyard_rust lanyard_target))

(test
 (name lan_foreign_types_emit)
 (modules lan_foreign_types_emit)
 (libraries kanon_kernel lanyard_rust lanyard_target))

(test
 (name lan_models_emit)
 (modules lan_models_emit)
 (libraries kanon_kernel kanon_surface lanyard_rust lanyard_target))

(test
 (name lan_connections_emit)
 (modules lan_connections_emit)
 (libraries kanon_kernel kanon_surface lanyard_rust lanyard_target))
