// Generated by lanyard's native Rust printer.
use std::sync::Arc;

#[derive(Clone, Debug, PartialEq, Eq)]
struct Nat(Vec<u8>);

#[derive(Debug)]
enum Error { Digit, Arithmetic, ModelRange, ModelByteRange, ModelUtf8 }
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Digit => f.write_str("invalid natural digit"),
            Self::Arithmetic => f.write_str("natural limb invariant failed"),
            Self::ModelRange => f.write_str("model Nat is outside 0..=i64::MAX"),
            Self::ModelByteRange => f.write_str("model text element is outside 0..=255"),
            Self::ModelUtf8 => f.write_str("model text is not valid UTF-8"),
        }
    }
}
impl std::error::Error for Error {}

impl Nat {
    fn canonical(bytes: Vec<u8>) -> Self {
        Self(bytes.into_iter().rev().skip_while(|b| *b == 0).collect::<Vec<_>>()
            .into_iter().rev().collect())
    }
    fn decimal(text: &str) -> Result<Self, Error> {
        text.bytes().try_fold(Self(Vec::new()), |n, c| {
            if c.is_ascii_digit() {
                n.scale(10)?.add(&Self::canonical(vec![c - b'0']))
            } else { Err(Error::Digit) }
        })
    }
    fn compare(&self, other: &Self) -> std::cmp::Ordering {
        self.0.len().cmp(&other.0.len()).then_with(|| self.0.iter().rev().cmp(other.0.iter().rev()))
    }
    fn finish(bytes: Vec<u8>, carry: u16) -> Result<Self, Error> {
        u8::try_from(carry).map_err(|_| Error::Arithmetic)
            .map(|last| Self::canonical(bytes.into_iter().chain(std::iter::once(last)).collect()))
    }
    fn add(&self, other: &Self) -> Result<Self, Error> {
        let (bytes, carry) = (0..self.0.len().max(other.0.len())).try_fold(
            (Vec::new(), 0_u16), |(bytes, carry), i| {
                let sum = self.0.get(i).map_or(0, |b| u16::from(*b))
                    + other.0.get(i).map_or(0, |b| u16::from(*b)) + carry;
                u8::try_from(sum % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), sum / 256))
            })?;
        Self::finish(bytes, carry)
    }
    fn sub(&self, other: &Self) -> Result<Self, Error> {
        if self.compare(other).is_lt() { Ok(Self(Vec::new())) } else {
        let (bytes, borrow) = self.0.iter().enumerate().try_fold(
            (Vec::new(), 0_u16), |(bytes, borrow), (i, byte)| {
                let rhs = other.0.get(i).map_or(0, |b| u16::from(*b)) + borrow;
                let lhs = u16::from(*byte);
                u8::try_from((lhs + 256 - rhs) % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), u16::from(lhs < rhs)))
            })?;
        if borrow == 0 { Ok(Self::canonical(bytes)) } else { Err(Error::Arithmetic) }
        }
    }
    fn scale(&self, factor: u8) -> Result<Self, Error> {
        let (bytes, carry) = self.0.iter().try_fold((Vec::new(), 0_u16), |(bytes, carry), byte| {
            let product = u16::from(*byte) * u16::from(factor) + carry;
            u8::try_from(product % 256).map_err(|_| Error::Arithmetic)
                .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), product / 256))
        })?;
        Self::finish(bytes, carry)
    }
    fn mul(&self, other: &Self) -> Result<Self, Error> {
        other.0.iter().enumerate().try_fold(Self(Vec::new()), |sum, (i, byte)| {
            let scaled = self.scale(*byte)?;
            let shifted = Self::canonical(std::iter::repeat_n(0, i).chain(scaled.0).collect());
            sum.add(&shifted)
        })
    }
}

#[derive(Clone, Debug)]
enum T6e6f6d696e616c28353a427974657329 { V0, V1(Box<(Nat, T6e6f6d696e616c28353a427974657329,)>) }

struct T636c6f7375726528736861726564286e6f6d696e616c28353a427974657329293b6e6f6d696e616c28353a42797465732929 {
    call: Box<dyn Fn(Arc<T6e6f6d696e616c28353a427974657329>) -> Result<T6e6f6d696e616c28353a427974657329, Error> + Send + Sync>,
    duplicate: Box<dyn Fn() -> Self + Send + Sync>,
}
impl Clone for T636c6f7375726528736861726564286e6f6d696e616c28353a427974657329293b6e6f6d696e616c28353a42797465732929 {
    fn clone(&self) -> Self { (self.duplicate)() }
}
impl std::fmt::Debug for T636c6f7375726528736861726564286e6f6d696e616c28353a427974657329293b6e6f6d696e616c28353a42797465732929 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str("Closure") }
}

struct T636c6f737572652873686172656428756e6974293b6e6f6d696e616c28353a42797465732929 {
    call: Box<dyn Fn(Arc<()>) -> Result<T6e6f6d696e616c28353a427974657329, Error> + Send + Sync>,
    duplicate: Box<dyn Fn() -> Self + Send + Sync>,
}
impl Clone for T636c6f737572652873686172656428756e6974293b6e6f6d696e616c28353a42797465732929 {
    fn clone(&self) -> Self { (self.duplicate)() }
}
impl std::fmt::Debug for T636c6f737572652873686172656428756e6974293b6e6f6d696e616c28353a42797465732929 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str("Closure") }
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum T73756d28756e69742c756e697429 { V0(()), V1(()) }

fn c_636170747572656424303a31(c0: Arc<T6e6f6d696e616c28353a427974657329>) -> T636c6f737572652873686172656428756e6974293b6e6f6d696e616c28353a42797465732929 {
    let saved_c0 = Arc::clone(&(c0));
    T636c6f737572652873686172656428756e6974293b6e6f6d696e616c28353a42797465732929 {
        call: Box::new(move |p0: Arc<()>| f_63617074757265642430(Arc::clone(&(c0)), p0)),
        duplicate: Box::new(move || c_636170747572656424303a31(Arc::clone(&(saved_c0)))),
    }
}

fn c_6e657374656424303a31() -> T636c6f7375726528736861726564286e6f6d696e616c28353a427974657329293b6e6f6d696e616c28353a42797465732929 {
    T636c6f7375726528736861726564286e6f6d696e616c28353a427974657329293b6e6f6d696e616c28353a42797465732929 {
        call: Box::new(move |p0: Arc<T6e6f6d696e616c28353a427974657329>| f_6e65737465642430(p0)),
        duplicate: Box::new(move || c_6e657374656424303a31()),
    }
}

fn f_5f5f6c616e5f746578745f30(a0: Arc<T6e6f6d696e616c28353a427974657329>) -> Result<topcoat::router::response::Response, Error> {
    Ok({ let __lan_text_arg = Arc::clone(&(a0)); let __lan_text = lan_model_text_to_4279746573(&__lan_text_arg)?; { let mut response = topcoat::router::response::Response::new(topcoat::router::Body::from(__lan_text)); response.headers_mut().insert(topcoat::router::header::CONTENT_TYPE, topcoat::router::HeaderValue::from_static("text/html; charset=utf-8")); response } })
}

fn f_5f5f6c616e5f746578745f31(a0: Arc<T6e6f6d696e616c28353a427974657329>) -> Result<T6e6f6d696e616c28353a427974657329, Error> {
    Ok({ let __lan_text_arg = Arc::clone(&(a0)); let __lan_text = lan_model_text_to_4279746573(&__lan_text_arg)?; lan_model_text_from_4279746573(__lan_text.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")) })
}

fn f_5f5f6c616e5f746578745f32(a0: Arc<T6e6f6d696e616c28353a427974657329>) -> Result<T6e6f6d696e616c28353a427974657329, Error> {
    Ok({ let __lan_text_arg = Arc::clone(&(a0)); let __lan_text = lan_model_text_to_4279746573(&__lan_text_arg)?; lan_model_text_from_4279746573(__lan_text.trim().to_owned()) })
}

fn f_5f5f6c616e5f746578745f33(a0: Arc<T6e6f6d696e616c28353a427974657329>) -> Result<topcoat::router::response::Response, Error> {
    Ok({ let __lan_text_arg = Arc::clone(&(a0)); let __lan_text = lan_model_text_to_4279746573(&__lan_text_arg)?; { let mut response = topcoat::router::response::Response::new(topcoat::router::Body::from(__lan_text)); response.headers_mut().insert(topcoat::router::header::CONTENT_TYPE, topcoat::router::HeaderValue::from_static("text/plain; charset=utf-8")); response } })
}

fn f_726177(a0: Arc<T6e6f6d696e616c28353a427974657329>) -> Result<topcoat::router::response::Response, Error> {
    Ok({ let __lan_text_arg = Arc::clone(&(a0)); let __lan_text = lan_model_text_to_4279746573(&__lan_text_arg)?; { let mut response = topcoat::router::response::Response::new(topcoat::router::Body::from(__lan_text)); response.headers_mut().insert(topcoat::router::header::CONTENT_TYPE, topcoat::router::HeaderValue::from_static("text/html; charset=utf-8")); response } })
}

fn f_72656e646572(a0: Arc<T6e6f6d696e616c28353a427974657329>) -> Result<topcoat::router::response::Response, Error> {
    f_5f5f6c616e5f746578745f30(Arc::new(f_5f5f6c616e5f746578745f31(Arc::clone(&(a0)))?))
}

fn f_63617074757265642430(a0: Arc<T6e6f6d696e616c28353a427974657329>, a1: Arc<()>) -> Result<T6e6f6d696e616c28353a427974657329, Error> {
    f_5f5f6c616e5f746578745f31(Arc::clone(&(a0)))
}

fn f_6361707475726564() -> Result<topcoat::router::response::Response, Error> {
    Ok({ let v0 = Arc::new(T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("60")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("99")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("97")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("112")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("116")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("117")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("114")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("101")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("100")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("62")?, T6e6f6d696e616c28353a427974657329::V0,))),))),))),))),))),))),))),))),))),)))); { let v1 = Arc::new(c_636170747572656424303a31(Arc::clone(&(v0)))); f_5f5f6c616e5f746578745f30(Arc::new(((Arc::clone(&(v1))).call)(Arc::new(()))?))? } })
}

fn f_6e65737465642430(a0: Arc<T6e6f6d696e616c28353a427974657329>) -> Result<T6e6f6d696e616c28353a427974657329, Error> {
    f_5f5f6c616e5f746578745f31(Arc::new(f_5f5f6c616e5f746578745f32(Arc::clone(&(a0)))?))
}

fn f_6e6573746564() -> Result<topcoat::router::response::Response, Error> {
    Ok({ let v0 = Arc::new(c_6e657374656424303a31()); f_5f5f6c616e5f746578745f30(Arc::new(((Arc::clone(&(v0))).call)(Arc::new(T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("32")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("60")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("110")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("101")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("115")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("116")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("101")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("100")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("62")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("32")?, T6e6f6d696e616c28353a427974657329::V0,))),))),))),))),))),))),))),))),))),)))))?))? })
}

fn f_706c61696e() -> Result<topcoat::router::response::Response, Error> {
    f_5f5f6c616e5f746578745f33(Arc::new(T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("60")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("112")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("108")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("97")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("105")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("110")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("62")?, T6e6f6d696e616c28353a427974657329::V0,))),))),))),))),))),))),)))))
}

fn f_62616442797465() -> Result<topcoat::router::response::Response, Error> {
    f_726177(Arc::new(T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("256")?, T6e6f6d696e616c28353a427974657329::V0,)))))
}

fn f_62616455746638() -> Result<topcoat::router::response::Response, Error> {
    f_726177(Arc::new(T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("255")?, T6e6f6d696e616c28353a427974657329::V0,)))))
}

fn f_626164457363617065() -> Result<topcoat::router::response::Response, Error> {
    f_72656e646572(Arc::new(T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("255")?, T6e6f6d696e616c28353a427974657329::V0,)))))
}

fn f_756e75736564() -> Result<topcoat::router::response::Response, Error> {
    Ok({ let v0 = f_5f5f6c616e5f746578745f31(Arc::new(T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("255")?, T6e6f6d696e616c28353a427974657329::V0,)))))?; f_726177(Arc::new(T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("111")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("107")?, T6e6f6d696e616c28353a427974657329::V0,))),)))))? })
}

fn f_6d61696e() -> Result<topcoat::router::response::Response, Error> {
    f_72656e646572(Arc::new(T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("60")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("104")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("101")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("108")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("108")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("111")?, T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::decimal("62")?, T6e6f6d696e616c28353a427974657329::V0,))),))),))),))),))),))),)))))
}


fn lan_model_to_i64(value: &Nat) -> Result<i64, Error> {
    value.0.iter().rev().try_fold(0_i64, |number, byte| {
        number.checked_mul(256).and_then(|number| number.checked_add(i64::from(*byte)))
            .ok_or(Error::ModelRange)
    })
}
fn lan_model_from_i64(value: i64) -> Result<Nat, Error> {
    if value < 0 { Err(Error::ModelRange) }
    else { Ok(Nat::canonical(value.to_le_bytes().to_vec())) }
}

fn lan_model_text_to_4279746573(value: &T6e6f6d696e616c28353a427974657329) -> Result<String, Error> {
    std::iter::successors(Some(value), |node| match node {
        T6e6f6d696e616c28353a427974657329::V0 => None,
        T6e6f6d696e616c28353a427974657329::V1(fields) => Some(&fields.1),
    }).filter_map(|node| match node {
        T6e6f6d696e616c28353a427974657329::V0 => None,
        T6e6f6d696e616c28353a427974657329::V1(fields) => Some(match fields.0.0.as_slice() {
            [] => Ok(0),
            [byte] => Ok(*byte),
            [_, _, ..] => Err(Error::ModelByteRange),
        }),
    }).collect::<Result<Vec<u8>, Error>>()
        .and_then(|bytes| String::from_utf8(bytes).map_err(|_error| Error::ModelUtf8))
}
fn lan_model_text_from_4279746573(value: String) -> T6e6f6d696e616c28353a427974657329 {
    value.bytes().rev().fold(T6e6f6d696e616c28353a427974657329::V0, |tail, byte| {
        T6e6f6d696e616c28353a427974657329::V1(Box::new((Nat::canonical(vec![byte]), tail)))
    })
}

async fn observe(value: Result<topcoat::router::response::Response, Error>, expected: &str, content_type: &str) -> Option<bool> {
    let (parts, body) = value.ok()?.into_parts();
    let bytes = topcoat::router::to_bytes(body, 8192).await.ok()?;
    Some(parts.status == topcoat::router::StatusCode::OK
        && parts.headers.get(topcoat::router::header::CONTENT_TYPE)? == content_type
        && bytes.as_ref() == expected.as_bytes())
}
#[tokio::main(flavor = "current_thread")]
async fn main() {
    println!("HTML0 {}", observe(f_726177(Arc::new(lan_model_text_from_4279746573("".to_owned()))), "", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML1 {}", observe(f_72656e646572(Arc::new(lan_model_text_from_4279746573("".to_owned()))), "", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML2 {}", observe(f_726177(Arc::new(lan_model_text_from_4279746573("hello".to_owned()))), "hello", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML3 {}", observe(f_72656e646572(Arc::new(lan_model_text_from_4279746573("hello".to_owned()))), "hello", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML4 {}", observe(f_726177(Arc::new(lan_model_text_from_4279746573("café".to_owned()))), "café", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML5 {}", observe(f_72656e646572(Arc::new(lan_model_text_from_4279746573("café".to_owned()))), "café", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML6 {}", observe(f_726177(Arc::new(lan_model_text_from_4279746573("日😀".to_owned()))), "日😀", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML7 {}", observe(f_72656e646572(Arc::new(lan_model_text_from_4279746573("日😀".to_owned()))), "日😀", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML8 {}", observe(f_726177(Arc::new(lan_model_text_from_4279746573("a\u{0}b".to_owned()))), "a\u{0}b", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML9 {}", observe(f_72656e646572(Arc::new(lan_model_text_from_4279746573("a\u{0}b".to_owned()))), "a\u{0}b", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML10 {}", observe(f_726177(Arc::new(lan_model_text_from_4279746573("a\u{d}\u{a}\u{d}\u{a}X-Header:yes".to_owned()))), "a\u{d}\u{a}\u{d}\u{a}X-Header:yes", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML11 {}", observe(f_72656e646572(Arc::new(lan_model_text_from_4279746573("a\u{d}\u{a}\u{d}\u{a}X-Header:yes".to_owned()))), "a\u{d}\u{a}\u{d}\u{a}X-Header:yes", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML12 {}", observe(f_726177(Arc::new(lan_model_text_from_4279746573("<b>&</b>".to_owned()))), "<b>&</b>", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML13 {}", observe(f_72656e646572(Arc::new(lan_model_text_from_4279746573("<b>&</b>".to_owned()))), "&lt;b&gt;&amp;&lt;/b&gt;", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML14 {}", observe(f_726177(Arc::new(lan_model_text_from_4279746573("&lt;&amp;".to_owned()))), "&lt;&amp;", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML15 {}", observe(f_72656e646572(Arc::new(lan_model_text_from_4279746573("&lt;&amp;".to_owned()))), "&amp;lt;&amp;amp;", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML16 {}", observe(f_726177(Arc::new(lan_model_text_from_4279746573("\"'=/".to_owned()))), "\"'=/", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML17 {}", observe(f_72656e646572(Arc::new(lan_model_text_from_4279746573("\"'=/".to_owned()))), "\"'=/", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML18 {}", observe(f_6361707475726564(), "&lt;captured&gt;", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML19 {}", observe(f_6e6573746564(), "&lt;nested&gt;", "text/html; charset=utf-8").await.unwrap_or(false));
    println!("HTML20 {}", observe(f_706c61696e(), "<plain>", "text/plain; charset=utf-8").await.unwrap_or(false));
    println!("HTML21 {}", format!("{:?}", f_62616442797465()) == "Err(ModelByteRange)");
    println!("HTML22 {}", format!("{:?}", f_62616455746638()) == "Err(ModelUtf8)");
    println!("HTML23 {}", format!("{:?}", f_626164457363617065()) == "Err(ModelUtf8)");
    println!("HTML24 {}", format!("{:?}", f_756e75736564()) == "Err(ModelUtf8)");
}
