// Generated by lanyard's native Rust printer.
use std::sync::Arc;

#[derive(Clone, Debug, PartialEq, Eq)]
struct Nat(Vec<u8>);

#[derive(Debug)]
enum Error { Digit, Arithmetic, Database(toasty::Error) }
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Digit => f.write_str("invalid natural digit"),
            Self::Arithmetic => f.write_str("natural limb invariant failed"),
            Self::Database(error) => std::fmt::Display::fmt(error, f),
        }
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Digit | Self::Arithmetic => None,
            Self::Database(error) => Some(error),
        }
    }
}
impl From<toasty::Error> for Error {
    fn from(error: toasty::Error) -> Self { Self::Database(error) }
}

impl Nat {
    fn canonical(bytes: Vec<u8>) -> Self {
        Self(bytes.into_iter().rev().skip_while(|b| *b == 0).collect::<Vec<_>>()
            .into_iter().rev().collect())
    }
    fn decimal(text: &str) -> Result<Self, Error> {
        text.bytes().try_fold(Self(Vec::new()), |n, c| {
            if c.is_ascii_digit() {
                n.scale(10)?.add(&Self::canonical(vec![c - b'0']))
            } else { Err(Error::Digit) }
        })
    }
    fn compare(&self, other: &Self) -> std::cmp::Ordering {
        self.0.len().cmp(&other.0.len()).then_with(|| self.0.iter().rev().cmp(other.0.iter().rev()))
    }
    fn finish(bytes: Vec<u8>, carry: u16) -> Result<Self, Error> {
        u8::try_from(carry).map_err(|_| Error::Arithmetic)
            .map(|last| Self::canonical(bytes.into_iter().chain(std::iter::once(last)).collect()))
    }
    fn add(&self, other: &Self) -> Result<Self, Error> {
        let (bytes, carry) = (0..self.0.len().max(other.0.len())).try_fold(
            (Vec::new(), 0_u16), |(bytes, carry), i| {
                let sum = self.0.get(i).map_or(0, |b| u16::from(*b))
                    + other.0.get(i).map_or(0, |b| u16::from(*b)) + carry;
                u8::try_from(sum % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), sum / 256))
            })?;
        Self::finish(bytes, carry)
    }
    fn sub(&self, other: &Self) -> Result<Self, Error> {
        if self.compare(other).is_lt() { Ok(Self(Vec::new())) } else {
        let (bytes, borrow) = self.0.iter().enumerate().try_fold(
            (Vec::new(), 0_u16), |(bytes, borrow), (i, byte)| {
                let rhs = other.0.get(i).map_or(0, |b| u16::from(*b)) + borrow;
                let lhs = u16::from(*byte);
                u8::try_from((lhs + 256 - rhs) % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), u16::from(lhs < rhs)))
            })?;
        if borrow == 0 { Ok(Self::canonical(bytes)) } else { Err(Error::Arithmetic) }
        }
    }
    fn scale(&self, factor: u8) -> Result<Self, Error> {
        let (bytes, carry) = self.0.iter().try_fold((Vec::new(), 0_u16), |(bytes, carry), byte| {
            let product = u16::from(*byte) * u16::from(factor) + carry;
            u8::try_from(product % 256).map_err(|_| Error::Arithmetic)
                .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), product / 256))
        })?;
        Self::finish(bytes, carry)
    }
    fn mul(&self, other: &Self) -> Result<Self, Error> {
        other.0.iter().enumerate().try_fold(Self(Vec::new()), |sum, (i, byte)| {
            let scaled = self.scale(*byte)?;
            let shifted = Self::canonical(std::iter::repeat_n(0, i).chain(scaled.0).collect());
            sum.add(&shifted)
        })
    }
}

#[derive(Clone, Debug)]
enum T6e6f6d696e616c28353a427974657329 { V0, V1(Box<(Nat, T6e6f6d696e616c28353a427974657329,)>) }

#[derive(Clone, Debug, PartialEq, Eq)]
struct T70726f64756374286e61742c6e617429 { f0: Nat, f1: Nat }

#[derive(Clone, Debug, PartialEq, Eq)]
enum T73756d28756e69742c756e697429 { V0(()), V1(()) }

fn f_6d6f7665466f726d(a0: topcoat::router::content::Form<topcoat::router::Uri>) -> Result<topcoat::router::content::Form<topcoat::router::Uri>, Error> {
    Ok(a0)
}

fn f_6d6f76654465666572726564(a0: toasty::Deferred<topcoat::router::Uri>) -> Result<toasty::Deferred<topcoat::router::Uri>, Error> {
    Ok(a0)
}

fn f_6d6f76654e6573746564(a0: topcoat::router::content::Form<toasty::Deferred<topcoat::router::Uri>>) -> Result<topcoat::router::content::Form<toasty::Deferred<topcoat::router::Uri>>, Error> {
    Ok(a0)
}

fn f_6d6f766552657665727365(a0: toasty::Deferred<topcoat::router::content::Form<topcoat::router::Uri>>) -> Result<toasty::Deferred<topcoat::router::content::Form<topcoat::router::Uri>>, Error> {
    Ok(a0)
}

fn f_6d6f766550616972(a0: topcoat::router::content::Form<T70726f64756374286e61742c6e617429>) -> Result<topcoat::router::content::Form<T70726f64756374286e61742c6e617429>, Error> {
    Ok(a0)
}

fn f_6d6f76654279746573(a0: toasty::Deferred<T6e6f6d696e616c28353a427974657329>) -> Result<toasty::Deferred<T6e6f6d696e616c28353a427974657329>, Error> {
    Ok(a0)
}

fn f_64697363617264(a0: Arc<topcoat::router::content::Form<topcoat::router::Uri>>) -> Result<(), Error> {
    Ok(())
}

fn f_7265757365(a0: Arc<topcoat::router::content::Form<topcoat::router::Uri>>) -> Result<(), Error> {
    Ok({ let v1 = f_64697363617264(Arc::clone(&(a0)))?; f_64697363617264(Arc::clone(&(a0)))? })
}

async fn f_6b656570(a0: Arc<toasty::Db>, a1: Arc<topcoat::router::content::Form<topcoat::router::Uri>>) -> Result<(), Error> {
    Ok({ let v2 = { let __lan_arg_0 = Arc::clone(&(a0)); (&*(__lan_arg_0)).push_schema().await? }; f_7265757365(Arc::clone(&(a1)))? })
}

async fn f_6b6565704f776e6564(a0: Arc<toasty::Db>, a1: toasty::Deferred<topcoat::router::Uri>) -> Result<toasty::Deferred<topcoat::router::Uri>, Error> {
    Ok({ let v2 = { let __lan_arg_0 = Arc::clone(&(a0)); (&*(__lan_arg_0)).push_schema().await? }; f_6d6f76654465666572726564(a1)? })
}
