// Generated by lanyard's native Rust printer.
use std::sync::Arc;

#[derive(Clone, Debug, PartialEq, Eq)]
struct Nat(Vec<u8>);

#[derive(Debug)]
enum Error { Digit, Arithmetic, Database(toasty::Error), ModelRange }
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Digit => f.write_str("invalid natural digit"),
            Self::Arithmetic => f.write_str("natural limb invariant failed"),
            Self::Database(error) => std::fmt::Display::fmt(error, f),
            Self::ModelRange => f.write_str("model Nat is outside 0..=i64::MAX"),
        }
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Digit | Self::Arithmetic | Self::ModelRange => None,
            Self::Database(error) => Some(error),
        }
    }
}
impl From<toasty::Error> for Error {
    fn from(error: toasty::Error) -> Self { Self::Database(error) }
}

impl Nat {
    fn canonical(bytes: Vec<u8>) -> Self {
        Self(bytes.into_iter().rev().skip_while(|b| *b == 0).collect::<Vec<_>>()
            .into_iter().rev().collect())
    }
    fn decimal(text: &str) -> Result<Self, Error> {
        text.bytes().try_fold(Self(Vec::new()), |n, c| {
            if c.is_ascii_digit() {
                n.scale(10)?.add(&Self::canonical(vec![c - b'0']))
            } else { Err(Error::Digit) }
        })
    }
    fn compare(&self, other: &Self) -> std::cmp::Ordering {
        self.0.len().cmp(&other.0.len()).then_with(|| self.0.iter().rev().cmp(other.0.iter().rev()))
    }
    fn finish(bytes: Vec<u8>, carry: u16) -> Result<Self, Error> {
        u8::try_from(carry).map_err(|_| Error::Arithmetic)
            .map(|last| Self::canonical(bytes.into_iter().chain(std::iter::once(last)).collect()))
    }
    fn add(&self, other: &Self) -> Result<Self, Error> {
        let (bytes, carry) = (0..self.0.len().max(other.0.len())).try_fold(
            (Vec::new(), 0_u16), |(bytes, carry), i| {
                let sum = self.0.get(i).map_or(0, |b| u16::from(*b))
                    + other.0.get(i).map_or(0, |b| u16::from(*b)) + carry;
                u8::try_from(sum % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), sum / 256))
            })?;
        Self::finish(bytes, carry)
    }
    fn sub(&self, other: &Self) -> Result<Self, Error> {
        if self.compare(other).is_lt() { Ok(Self(Vec::new())) } else {
        let (bytes, borrow) = self.0.iter().enumerate().try_fold(
            (Vec::new(), 0_u16), |(bytes, borrow), (i, byte)| {
                let rhs = other.0.get(i).map_or(0, |b| u16::from(*b)) + borrow;
                let lhs = u16::from(*byte);
                u8::try_from((lhs + 256 - rhs) % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), u16::from(lhs < rhs)))
            })?;
        if borrow == 0 { Ok(Self::canonical(bytes)) } else { Err(Error::Arithmetic) }
        }
    }
    fn scale(&self, factor: u8) -> Result<Self, Error> {
        let (bytes, carry) = self.0.iter().try_fold((Vec::new(), 0_u16), |(bytes, carry), byte| {
            let product = u16::from(*byte) * u16::from(factor) + carry;
            u8::try_from(product % 256).map_err(|_| Error::Arithmetic)
                .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), product / 256))
        })?;
        Self::finish(bytes, carry)
    }
    fn mul(&self, other: &Self) -> Result<Self, Error> {
        other.0.iter().enumerate().try_fold(Self(Vec::new()), |sum, (i, byte)| {
            let scaled = self.scale(*byte)?;
            let shifted = Self::canonical(std::iter::repeat_n(0, i).chain(scaled.0).collect());
            sum.add(&shifted)
        })
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct T70726f64756374286e61742c6e617429 { f0: Nat, f1: Nat }

#[derive(Clone, Debug, PartialEq, Eq)]
enum T73756d28756e69742c756e697429 { V0(()), V1(()) }

fn f_6974656d() -> Result<T70726f64756374286e61742c6e617429, Error> {
    Ok(T70726f64756374286e61742c6e617429 { f0: Nat::decimal("7")?, f1: Nat::decimal("42")? })
}

async fn f_637265617465(a0: Arc<toasty::Db>) -> Result<T70726f64756374286e61742c6e617429, Error> {
    Ok({ let __lan_value = Arc::new(f_6974656d()?); let __lan_db_arg = Arc::clone(&(a0)); let mut __lan_db = (*__lan_db_arg).clone(); let __lan_row = toasty::create!(LanModel436f756e746572 { id: lan_model_to_i64(&__lan_value.f0)?, f_76616c7565: lan_model_to_i64(&__lan_value.f1)? }).exec(&mut __lan_db).await?; T70726f64756374286e61742c6e617429 { f0: lan_model_from_i64(__lan_row.id)?, f1: lan_model_from_i64(__lan_row.f_76616c7565)? } })
}

async fn f_6c6f6f6b7570(a0: Arc<Nat>, a1: Arc<toasty::Db>) -> Result<T70726f64756374286e61742c6e617429, Error> {
    Ok({ let __lan_value = Arc::clone(&(a0)); let __lan_db_arg = Arc::clone(&(a1)); let mut __lan_db = (*__lan_db_arg).clone(); let __lan_row = LanModel436f756e746572::get_by_id(&mut __lan_db, &lan_model_to_i64(&__lan_value)?).await?; T70726f64756374286e61742c6e617429 { f0: lan_model_from_i64(__lan_row.id)?, f1: lan_model_from_i64(__lan_row.f_76616c7565)? } })
}

async fn f_726f756e6474726970(a0: Arc<toasty::Db>) -> Result<T70726f64756374286e61742c6e617429, Error> {
    Ok({ let v1 = Arc::new(f_637265617465(Arc::clone(&(a0))).await?); f_6c6f6f6b7570(Arc::new({ let T70726f64756374286e61742c6e617429 { f0: p0, f1: p1 } = (*(Arc::clone(&(v1)))).clone(); p0 }), Arc::clone(&(a0))).await? })
}

async fn f_63726561746553696e676c65(a0: Arc<T70726f64756374286e61742c6e617429>, a1: Arc<toasty::Db>) -> Result<T70726f64756374286e61742c6e617429, Error> {
    Ok({ let __lan_value = Arc::clone(&(a0)); let __lan_db_arg = Arc::clone(&(a1)); let mut __lan_db = (*__lan_db_arg).clone(); let __lan_row = toasty::create!(LanModel53696e676c65 { f_76616c7565: lan_model_to_i64(&__lan_value.f0)?, id: lan_model_to_i64(&__lan_value.f1)? }).exec(&mut __lan_db).await?; T70726f64756374286e61742c6e617429 { f0: lan_model_from_i64(__lan_row.f_76616c7565)?, f1: lan_model_from_i64(__lan_row.id)? } })
}

async fn f_6c6f6f6b757053696e676c65(a0: Arc<Nat>, a1: Arc<toasty::Db>) -> Result<T70726f64756374286e61742c6e617429, Error> {
    Ok({ let __lan_value = Arc::clone(&(a0)); let __lan_db_arg = Arc::clone(&(a1)); let mut __lan_db = (*__lan_db_arg).clone(); let __lan_row = LanModel53696e676c65::get_by_id(&mut __lan_db, &lan_model_to_i64(&__lan_value)?).await?; T70726f64756374286e61742c6e617429 { f0: lan_model_from_i64(__lan_row.f_76616c7565)?, f1: lan_model_from_i64(__lan_row.id)? } })
}

#[derive(Debug, toasty::Model)]
struct LanModel436f756e746572 {
    #[key]
    id: i64,
    f_76616c7565: i64,
}

#[derive(Debug, toasty::Model)]
struct LanModel53696e676c65 {
    f_76616c7565: i64,
    #[key]
    id: i64,
}

fn lan_model_to_i64(value: &Nat) -> Result<i64, Error> {
    value.0.iter().rev().try_fold(0_i64, |number, byte| {
        number.checked_mul(256).and_then(|number| number.checked_add(i64::from(*byte)))
            .ok_or(Error::ModelRange)
    })
}
fn lan_model_from_i64(value: i64) -> Result<Nat, Error> {
    if value < 0 { Err(Error::ModelRange) }
    else { Ok(Nat::canonical(value.to_le_bytes().to_vec())) }
}
