// Generated by lanyard's native Rust printer.
use std::sync::Arc;

#[derive(Clone, Debug, PartialEq, Eq)]
struct Nat(Vec<u8>);

#[derive(Debug)]
enum Error { Digit, Arithmetic }
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Digit => f.write_str("invalid natural digit"),
            Self::Arithmetic => f.write_str("natural limb invariant failed"),
        }
    }
}
impl std::error::Error for Error {}

impl Nat {
    fn canonical(bytes: Vec<u8>) -> Self {
        Self(bytes.into_iter().rev().skip_while(|b| *b == 0).collect::<Vec<_>>()
            .into_iter().rev().collect())
    }
    fn decimal(text: &str) -> Result<Self, Error> {
        text.bytes().try_fold(Self(Vec::new()), |n, c| {
            if c.is_ascii_digit() {
                n.scale(10)?.add(&Self::canonical(vec![c - b'0']))
            } else { Err(Error::Digit) }
        })
    }
    fn compare(&self, other: &Self) -> std::cmp::Ordering {
        self.0.len().cmp(&other.0.len()).then_with(|| self.0.iter().rev().cmp(other.0.iter().rev()))
    }
    fn finish(bytes: Vec<u8>, carry: u16) -> Result<Self, Error> {
        u8::try_from(carry).map_err(|_| Error::Arithmetic)
            .map(|last| Self::canonical(bytes.into_iter().chain(std::iter::once(last)).collect()))
    }
    fn add(&self, other: &Self) -> Result<Self, Error> {
        let (bytes, carry) = (0..self.0.len().max(other.0.len())).try_fold(
            (Vec::new(), 0_u16), |(bytes, carry), i| {
                let sum = self.0.get(i).map_or(0, |b| u16::from(*b))
                    + other.0.get(i).map_or(0, |b| u16::from(*b)) + carry;
                u8::try_from(sum % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), sum / 256))
            })?;
        Self::finish(bytes, carry)
    }
    fn sub(&self, other: &Self) -> Result<Self, Error> {
        if self.compare(other).is_lt() { Ok(Self(Vec::new())) } else {
        let (bytes, borrow) = self.0.iter().enumerate().try_fold(
            (Vec::new(), 0_u16), |(bytes, borrow), (i, byte)| {
                let rhs = other.0.get(i).map_or(0, |b| u16::from(*b)) + borrow;
                let lhs = u16::from(*byte);
                u8::try_from((lhs + 256 - rhs) % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), u16::from(lhs < rhs)))
            })?;
        if borrow == 0 { Ok(Self::canonical(bytes)) } else { Err(Error::Arithmetic) }
        }
    }
    fn scale(&self, factor: u8) -> Result<Self, Error> {
        let (bytes, carry) = self.0.iter().try_fold((Vec::new(), 0_u16), |(bytes, carry), byte| {
            let product = u16::from(*byte) * u16::from(factor) + carry;
            u8::try_from(product % 256).map_err(|_| Error::Arithmetic)
                .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), product / 256))
        })?;
        Self::finish(bytes, carry)
    }
    fn mul(&self, other: &Self) -> Result<Self, Error> {
        other.0.iter().enumerate().try_fold(Self(Vec::new()), |sum, (i, byte)| {
            let scaled = self.scale(*byte)?;
            let shifted = Self::canonical(std::iter::repeat_n(0, i).chain(scaled.0).collect());
            sum.add(&shifted)
        })
    }
}

struct T636c6f73757265283b6e617429 {
    call: Box<dyn Fn() -> Result<Nat, Error> + Send + Sync>,
    duplicate: Box<dyn Fn() -> Self + Send + Sync>,
}
impl Clone for T636c6f73757265283b6e617429 {
    fn clone(&self) -> Self { (self.duplicate)() }
}
impl std::fmt::Debug for T636c6f73757265283b6e617429 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str("Closure") }
}

struct T636c6f73757265286e61743b6e617429 {
    call: Box<dyn Fn(Nat) -> Result<Nat, Error> + Send + Sync>,
    duplicate: Box<dyn Fn() -> Self + Send + Sync>,
}
impl Clone for T636c6f73757265286e61743b6e617429 {
    fn clone(&self) -> Self { (self.duplicate)() }
}
impl std::fmt::Debug for T636c6f73757265286e61743b6e617429 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str("Closure") }
}

struct T636c6f737572652873686172656428636c6f7375726528736861726564286e6174293b6e617429293b6e617429 {
    call: Box<dyn Fn(Arc<T636c6f7375726528736861726564286e6174293b6e617429>) -> Result<Nat, Error> + Send + Sync>,
    duplicate: Box<dyn Fn() -> Self + Send + Sync>,
}
impl Clone for T636c6f737572652873686172656428636c6f7375726528736861726564286e6174293b6e617429293b6e617429 {
    fn clone(&self) -> Self { (self.duplicate)() }
}
impl std::fmt::Debug for T636c6f737572652873686172656428636c6f7375726528736861726564286e6174293b6e617429293b6e617429 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str("Closure") }
}

struct T636c6f7375726528736861726564286e6174293b6e617429 {
    call: Box<dyn Fn(Arc<Nat>) -> Result<Nat, Error> + Send + Sync>,
    duplicate: Box<dyn Fn() -> Self + Send + Sync>,
}
impl Clone for T636c6f7375726528736861726564286e6174293b6e617429 {
    fn clone(&self) -> Self { (self.duplicate)() }
}
impl std::fmt::Debug for T636c6f7375726528736861726564286e6174293b6e617429 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str("Closure") }
}

#[derive(Clone, Debug)]
struct T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929 { f0: T636c6f7375726528736861726564286e6174293b6e617429 }

#[derive(Clone, Debug)]
enum T73756d28636c6f7375726528736861726564286e6174293b6e6174292c6e617429 { V0(T636c6f7375726528736861726564286e6174293b6e617429), V1(Nat) }

#[derive(Clone, Debug, PartialEq, Eq)]
enum T73756d28756e69742c756e697429 { V0(()), V1(()) }

fn c_65726173656424303a31() -> T636c6f7375726528736861726564286e6174293b6e617429 {
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_6572617365642430(p0)),
        duplicate: Box::new(move || c_65726173656424303a31()),
    }
}

fn c_68696768657224303a31() -> T636c6f7375726528736861726564286e6174293b6e617429 {
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_6869676865722430(p0)),
        duplicate: Box::new(move || c_68696768657224303a31()),
    }
}

fn c_6869676865724f7264657224303a31() -> T636c6f737572652873686172656428636c6f7375726528736861726564286e6174293b6e617429293b6e617429 {
    T636c6f737572652873686172656428636c6f7375726528736861726564286e6174293b6e617429293b6e617429 {
        call: Box::new(move |p0: Arc<T636c6f7375726528736861726564286e6174293b6e617429>| f_6869676865724f726465722430(p0)),
        duplicate: Box::new(move || c_6869676865724f7264657224303a31()),
    }
}

fn c_6c6f63616c24303a31() -> T636c6f7375726528736861726564286e6174293b6e617429 {
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_6c6f63616c2430(p0)),
        duplicate: Box::new(move || c_6c6f63616c24303a31()),
    }
}

fn c_6e65737465644361707475726524303a31() -> T636c6f7375726528736861726564286e6174293b6e617429 {
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_6e6573746564436170747572652430(p0)),
        duplicate: Box::new(move || c_6e65737465644361707475726524303a31()),
    }
}

fn c_6e65737465645061636b24303a31(c0: Arc<T636c6f7375726528736861726564286e6174293b6e617429>) -> T636c6f7375726528736861726564286e6174293b6e617429 {
    let saved_c0 = Arc::clone(&(c0));
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_6e65737465645061636b2430(Arc::clone(&(c0)), p0)),
        duplicate: Box::new(move || c_6e65737465645061636b24303a31(Arc::clone(&(saved_c0)))),
    }
}

fn c_6e6f4361707475726524303a31() -> T636c6f7375726528736861726564286e6174293b6e617429 {
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_6e6f436170747572652430(p0)),
        duplicate: Box::new(move || c_6e6f4361707475726524303a31()),
    }
}

fn c_6e756c6c61727924303a30() -> T636c6f73757265283b6e617429 {
    T636c6f73757265283b6e617429 {
        call: Box::new(move || f_6e756c6c6172792430()),
        duplicate: Box::new(move || c_6e756c6c61727924303a30()),
    }
}

fn c_6f6e654361707475726524303a31(c0: Nat) -> T636c6f7375726528736861726564286e6174293b6e617429 {
    let saved_c0 = (c0).clone();
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_6f6e65436170747572652430((c0).clone(), p0)),
        duplicate: Box::new(move || c_6f6e654361707475726524303a31((saved_c0).clone())),
    }
}

fn c_6f72646572656424303a31(c0: Arc<Nat>, c1: Arc<Nat>) -> T636c6f7375726528736861726564286e6174293b6e617429 {
    let saved_c0 = Arc::clone(&(c0));
    let saved_c1 = Arc::clone(&(c1));
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_6f7264657265642430(Arc::clone(&(c0)), Arc::clone(&(c1)), p0)),
        duplicate: Box::new(move || c_6f72646572656424303a31(Arc::clone(&(saved_c0)), Arc::clone(&(saved_c1)))),
    }
}

fn c_6f776e656424303a31() -> T636c6f73757265286e61743b6e617429 {
    T636c6f73757265286e61743b6e617429 {
        call: Box::new(move |p0: Nat| f_6f776e65642430(p0)),
        duplicate: Box::new(move || c_6f776e656424303a31()),
    }
}

fn c_7061636b24303a31(c0: Arc<Nat>) -> T636c6f7375726528736861726564286e6174293b6e617429 {
    let saved_c0 = Arc::clone(&(c0));
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_7061636b2430(Arc::clone(&(c0)), p0)),
        duplicate: Box::new(move || c_7061636b24303a31(Arc::clone(&(saved_c0)))),
    }
}

fn c_73756d436c6f7375726524303a31() -> T636c6f7375726528736861726564286e6174293b6e617429 {
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_73756d436c6f737572652430(p0)),
        duplicate: Box::new(move || c_73756d436c6f7375726524303a31()),
    }
}

fn f_6170706c79(a0: Arc<T636c6f7375726528736861726564286e6174293b6e617429>, a1: Arc<Nat>) -> Result<Nat, Error> {
    ((Arc::clone(&(a0))).call)(Arc::clone(&(a1)))
}

fn f_7477696365(a0: Arc<T636c6f7375726528736861726564286e6174293b6e617429>, a1: Arc<Nat>) -> Result<Nat, Error> {
    ((Arc::clone(&(a0))).call)(Arc::new(((Arc::clone(&(a0))).call)(Arc::clone(&(a1)))?))
}

fn f_7061636b2430(a0: Arc<Nat>, a1: Arc<Nat>) -> Result<Nat, Error> {
    ((*(Arc::clone(&(a0)))).clone()).add(&((*(Arc::clone(&(a1)))).clone()))
}

fn f_7061636b(a0: Arc<Nat>) -> Result<T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929, Error> {
    Ok(T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929 { f0: c_7061636b24303a31(Arc::clone(&(a0))) })
}

fn f_6361707475726564() -> Result<Nat, Error> {
    f_6170706c79(Arc::new({ let T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929 { f0: p0 } = f_7061636b(Arc::new(Nat::decimal("17")?))?; p0 }), Arc::new(Nat::decimal("5")?))
}

fn f_7265706561746564() -> Result<Nat, Error> {
    f_7477696365(Arc::new({ let T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929 { f0: p0 } = f_7061636b(Arc::new(Nat::decimal("13")?))?; p0 }), Arc::new(Nat::decimal("7")?))
}

fn f_6c6f63616c2430(a0: Arc<Nat>) -> Result<Nat, Error> {
    ((*(Arc::clone(&(a0)))).clone()).mul(&(Nat::decimal("3")?))
}

fn f_6c6f63616c() -> Result<Nat, Error> {
    Ok({ let v0 = Arc::new(c_6c6f63616c24303a31()); (((Arc::clone(&(v0))).call)(Arc::new(Nat::decimal("11")?))?).add(&(((Arc::clone(&(v0))).call)(Arc::new(Nat::decimal("19")?))?))? })
}

fn f_6e6f436170747572652430(a0: Arc<Nat>) -> Result<Nat, Error> {
    ((*(Arc::clone(&(a0)))).clone()).add(&(Nat::decimal("1")?))
}

fn f_6e6f43617074757265() -> Result<Nat, Error> {
    f_6170706c79(Arc::new(c_6e6f4361707475726524303a31()), Arc::new(Nat::decimal("41")?))
}

fn f_6f7264657265642430(a0: Arc<Nat>, a1: Arc<Nat>, a2: Arc<Nat>) -> Result<Nat, Error> {
    (((*(Arc::clone(&(a0)))).clone()).sub(&((*(Arc::clone(&(a1)))).clone()))?).add(&((*(Arc::clone(&(a2)))).clone()))
}

fn f_6f726465726564(a0: Arc<Nat>, a1: Arc<Nat>) -> Result<T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929, Error> {
    Ok(T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929 { f0: c_6f72646572656424303a31(Arc::clone(&(a0)), Arc::clone(&(a1))) })
}

fn f_636170747572654f72646572() -> Result<Nat, Error> {
    f_6170706c79(Arc::new({ let T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929 { f0: p0 } = f_6f726465726564(Arc::new(Nat::decimal("19")?), Arc::new(Nat::decimal("7")?))?; p0 }), Arc::new(Nat::decimal("2")?))
}

fn f_6170706c794f6e65(a0: T636c6f73757265286e61743b6e617429, a1: Nat) -> Result<Nat, Error> {
    ((a0).call)(a1)
}

fn f_6f776e65642430(a0: Nat) -> Result<Nat, Error> {
    Ok(a0)
}

fn f_6f776e6564() -> Result<Nat, Error> {
    f_6170706c794f6e65(c_6f776e656424303a31(), Nat::decimal("23")?)
}

fn f_6f6e65436170747572652430(a0: Nat, a1: Arc<Nat>) -> Result<Nat, Error> {
    Ok(a0)
}

fn f_6f6e6543617074757265(a0: Nat) -> Result<Nat, Error> {
    Ok({ let v1 = Arc::new(c_6f6e654361707475726524303a31(a0)); ((Arc::clone(&(v1))).call)(Arc::new(Nat::decimal("0")?))? })
}

fn f_6572617365417267(a0: Arc<T636c6f7375726528736861726564286e6174293b6e617429>) -> Result<Nat, Error> {
    ((Arc::clone(&(a0))).call)(Arc::new(Nat::decimal("31")?))
}

fn f_6572617365642430(a0: Arc<Nat>) -> Result<Nat, Error> {
    ((*(Arc::clone(&(a0)))).clone()).add(&(Nat::decimal("2")?))
}

fn f_657261736564() -> Result<Nat, Error> {
    f_6572617365417267(Arc::new(c_65726173656424303a31()))
}

fn f_666f726365(a0: Arc<T636c6f73757265283b6e617429>) -> Result<Nat, Error> {
    ((Arc::clone(&(a0))).call)()
}

fn f_6e756c6c6172792430() -> Result<Nat, Error> {
    Nat::decimal("29")
}

fn f_6e756c6c617279() -> Result<Nat, Error> {
    f_666f726365(Arc::new(c_6e756c6c61727924303a30()))
}

fn f_6e65737465645061636b2430(a0: Arc<T636c6f7375726528736861726564286e6174293b6e617429>, a1: Arc<Nat>) -> Result<Nat, Error> {
    ((Arc::clone(&(a0))).call)(Arc::new(((*(Arc::clone(&(a1)))).clone()).add(&(Nat::decimal("3")?))?))
}

fn f_6e65737465645061636b(a0: Arc<T636c6f7375726528736861726564286e6174293b6e617429>) -> Result<T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929, Error> {
    Ok(T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929 { f0: c_6e65737465645061636b24303a31(Arc::clone(&(a0))) })
}

fn f_6e6573746564436170747572652430(a0: Arc<Nat>) -> Result<Nat, Error> {
    ((*(Arc::clone(&(a0)))).clone()).mul(&(Nat::decimal("2")?))
}

fn f_6e657374656443617074757265() -> Result<Nat, Error> {
    f_6170706c79(Arc::new({ let T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929 { f0: p0 } = f_6e65737465645061636b(Arc::new(c_6e65737465644361707475726524303a31()))?; p0 }), Arc::new(Nat::decimal("11")?))
}

fn f_6869676865722430(a0: Arc<Nat>) -> Result<Nat, Error> {
    ((*(Arc::clone(&(a0)))).clone()).add(&(Nat::decimal("4")?))
}

fn f_686967686572(a0: Arc<T636c6f737572652873686172656428636c6f7375726528736861726564286e6174293b6e617429293b6e617429>) -> Result<Nat, Error> {
    ((Arc::clone(&(a0))).call)(Arc::new(c_68696768657224303a31()))
}

fn f_6869676865724f726465722430(a0: Arc<T636c6f7375726528736861726564286e6174293b6e617429>) -> Result<Nat, Error> {
    ((Arc::clone(&(a0))).call)(Arc::new(Nat::decimal("37")?))
}

fn f_6869676865724f72646572() -> Result<Nat, Error> {
    f_686967686572(Arc::new(c_6869676865724f7264657224303a31()))
}

fn f_63686f6f7365(a0: Arc<T73756d28636c6f7375726528736861726564286e6174293b6e6174292c6e617429>) -> Result<Nat, Error> {
    Ok(match (*(Arc::clone(&(a0)))).clone() { T73756d28636c6f7375726528736861726564286e6174293b6e6174292c6e617429::V0(v1) => { let v1 = Arc::new(v1); ((Arc::clone(&(v1))).call)(Arc::new(Nat::decimal("8")?))? }, T73756d28636c6f7375726528736861726564286e6174293b6e6174292c6e617429::V1(v1) => (*({ let v1 = Arc::new(v1); Arc::clone(&(v1)) })).clone() })
}

fn f_73756d436c6f737572652430(a0: Arc<Nat>) -> Result<Nat, Error> {
    ((*(Arc::clone(&(a0)))).clone()).add(&(Nat::decimal("9")?))
}

fn f_73756d436c6f73757265() -> Result<Nat, Error> {
    f_63686f6f7365(Arc::new(T73756d28636c6f7375726528736861726564286e6174293b6e6174292c6e617429::V0(c_73756d436c6f7375726524303a31())))
}
