// Generated by lanyard's native Rust printer.
use std::sync::Arc;

#[derive(Clone, Debug, PartialEq, Eq)]
struct Nat(Vec<u8>);

#[derive(Debug)]
enum Error { Digit, Arithmetic }
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Digit => f.write_str("invalid natural digit"),
            Self::Arithmetic => f.write_str("natural limb invariant failed"),
        }
    }
}
impl std::error::Error for Error {}

impl Nat {
    fn canonical(bytes: Vec<u8>) -> Self {
        Self(bytes.into_iter().rev().skip_while(|b| *b == 0).collect::<Vec<_>>()
            .into_iter().rev().collect())
    }
    fn decimal(text: &str) -> Result<Self, Error> {
        text.bytes().try_fold(Self(Vec::new()), |n, c| {
            if c.is_ascii_digit() {
                n.scale(10)?.add(&Self::canonical(vec![c - b'0']))
            } else { Err(Error::Digit) }
        })
    }
    fn compare(&self, other: &Self) -> std::cmp::Ordering {
        self.0.len().cmp(&other.0.len()).then_with(|| self.0.iter().rev().cmp(other.0.iter().rev()))
    }
    fn finish(bytes: Vec<u8>, carry: u16) -> Result<Self, Error> {
        u8::try_from(carry).map_err(|_| Error::Arithmetic)
            .map(|last| Self::canonical(bytes.into_iter().chain(std::iter::once(last)).collect()))
    }
    fn add(&self, other: &Self) -> Result<Self, Error> {
        let (bytes, carry) = (0..self.0.len().max(other.0.len())).try_fold(
            (Vec::new(), 0_u16), |(bytes, carry), i| {
                let sum = self.0.get(i).map_or(0, |b| u16::from(*b))
                    + other.0.get(i).map_or(0, |b| u16::from(*b)) + carry;
                u8::try_from(sum % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), sum / 256))
            })?;
        Self::finish(bytes, carry)
    }
    fn sub(&self, other: &Self) -> Result<Self, Error> {
        if self.compare(other).is_lt() { Ok(Self(Vec::new())) } else {
        let (bytes, borrow) = self.0.iter().enumerate().try_fold(
            (Vec::new(), 0_u16), |(bytes, borrow), (i, byte)| {
                let rhs = other.0.get(i).map_or(0, |b| u16::from(*b)) + borrow;
                let lhs = u16::from(*byte);
                u8::try_from((lhs + 256 - rhs) % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), u16::from(lhs < rhs)))
            })?;
        if borrow == 0 { Ok(Self::canonical(bytes)) } else { Err(Error::Arithmetic) }
        }
    }
    fn scale(&self, factor: u8) -> Result<Self, Error> {
        let (bytes, carry) = self.0.iter().try_fold((Vec::new(), 0_u16), |(bytes, carry), byte| {
            let product = u16::from(*byte) * u16::from(factor) + carry;
            u8::try_from(product % 256).map_err(|_| Error::Arithmetic)
                .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), product / 256))
        })?;
        Self::finish(bytes, carry)
    }
    fn mul(&self, other: &Self) -> Result<Self, Error> {
        other.0.iter().enumerate().try_fold(Self(Vec::new()), |sum, (i, byte)| {
            let scaled = self.scale(*byte)?;
            let shifted = Self::canonical(std::iter::repeat_n(0, i).chain(scaled.0).collect());
            sum.add(&shifted)
        })
    }
}

#[derive(Clone, Debug)]
enum T6e6f6d696e616c28363a43686f69636529 { V0(Box<(Nat,)>), V1(Box<(Nat,)>) }

#[derive(Clone, Debug)]
enum T6e6f6d696e616c28363a45726173656429 { V0(Box<(Nat,)>) }

#[derive(Clone, Debug)]
enum T6e6f6d696e616c28343a4576656e29 { V0, V1(Box<(T6e6f6d696e616c28333a4f646429,)>) }

#[derive(Clone, Debug)]
enum T6e6f6d696e616c28393a46756e6374696f6e7329 { V0, V1(Box<(T636c6f7375726528736861726564286e6174293b6e617429, T6e6f6d696e616c28393a46756e6374696f6e7329,)>) }

#[derive(Clone, Debug)]
enum T6e6f6d696e616c28343a4c69737429 { V0, V1(Box<(Nat, T6e6f6d696e616c28343a4c69737429,)>) }

#[derive(Clone, Debug)]
enum T6e6f6d696e616c28333a4f646429 { V0(Box<(T6e6f6d696e616c28343a4576656e29,)>) }

#[derive(Clone, Debug)]
enum T6e6f6d696e616c28343a5472656529 { V0(Box<(Nat,)>), V1(Box<(T6e6f6d696e616c28343a5472656529, T6e6f6d696e616c28343a5472656529,)>) }

#[derive(Clone, Debug)]
enum T6e6f6d696e616c28373a5772617070656429 { V0(Box<(T70726f64756374286e6f6d696e616c28343a4c697374292c6e617429,)>) }

struct T636c6f7375726528736861726564286e6174293b6e617429 {
    call: Box<dyn Fn(Arc<Nat>) -> Result<Nat, Error> + Send + Sync>,
    duplicate: Box<dyn Fn() -> Self + Send + Sync>,
}
impl Clone for T636c6f7375726528736861726564286e6174293b6e617429 {
    fn clone(&self) -> Self { (self.duplicate)() }
}
impl std::fmt::Debug for T636c6f7375726528736861726564286e6174293b6e617429 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str("Closure") }
}

#[derive(Clone, Debug)]
struct T70726f64756374286e6f6d696e616c28343a4c697374292c6e617429 { f0: T6e6f6d696e616c28343a4c69737429, f1: Nat }

#[derive(Clone, Debug, PartialEq, Eq)]
enum T73756d28756e69742c756e697429 { V0(()), V1(()) }

fn c_636170747572656424303a31(c0: Arc<T6e6f6d696e616c28343a4c69737429>) -> T636c6f7375726528736861726564286e6174293b6e617429 {
    let saved_c0 = Arc::clone(&(c0));
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_63617074757265642430(Arc::clone(&(c0)), p0)),
        duplicate: Box::new(move || c_636170747572656424303a31(Arc::clone(&(saved_c0)))),
    }
}

fn c_66756e6374696f6e7324303a31() -> T636c6f7375726528736861726564286e6174293b6e617429 {
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_66756e6374696f6e732430(p0)),
        duplicate: Box::new(move || c_66756e6374696f6e7324303a31()),
    }
}

fn f_73756d4c697374(a0: Arc<T6e6f6d696e616c28343a4c69737429>) -> Result<Nat, Error> {
    Ok(match (*(Arc::clone(&(a0)))).clone() { T6e6f6d696e616c28343a4c69737429::V0 => { Nat::decimal("0")? }, T6e6f6d696e616c28343a4c69737429::V1(payload1) => { let (v1, v2,) = *payload1; let v1 = Arc::new(v1); let v2 = Arc::new(v2); ((*(Arc::clone(&(v1)))).clone()).add(&(f_73756d4c697374(Arc::clone(&(v2)))?))? } })
}

fn f_73616d706c65() -> Result<T6e6f6d696e616c28343a4c69737429, Error> {
    Ok(T6e6f6d696e616c28343a4c69737429::V1(Box::new((Nat::decimal("7")?, T6e6f6d696e616c28343a4c69737429::V1(Box::new((Nat::decimal("11")?, T6e6f6d696e616c28343a4c69737429::V1(Box::new((Nat::decimal("13")?, T6e6f6d696e616c28343a4c69737429::V0,))),))),))))
}

fn f_746f74616c() -> Result<Nat, Error> {
    f_73756d4c697374(Arc::new(f_73616d706c65()?))
}

fn f_6964656e74697479(a0: Arc<T6e6f6d696e616c28343a4c69737429>) -> Result<T6e6f6d696e616c28343a4c69737429, Error> {
    Ok((*(Arc::clone(&(a0)))).clone())
}

fn f_73756d54726565(a0: Arc<T6e6f6d696e616c28343a5472656529>) -> Result<Nat, Error> {
    Ok(match (*(Arc::clone(&(a0)))).clone() { T6e6f6d696e616c28343a5472656529::V0(payload1) => (*({ let (v1,) = *payload1; let v1 = Arc::new(v1); Arc::clone(&(v1)) })).clone(), T6e6f6d696e616c28343a5472656529::V1(payload1) => { let (v1, v2,) = *payload1; let v1 = Arc::new(v1); let v2 = Arc::new(v2); (f_73756d54726565(Arc::clone(&(v1)))?).add(&(f_73756d54726565(Arc::clone(&(v2)))?))? } })
}

fn f_74726565() -> Result<T6e6f6d696e616c28343a5472656529, Error> {
    Ok(T6e6f6d696e616c28343a5472656529::V1(Box::new((T6e6f6d696e616c28343a5472656529::V0(Box::new((Nat::decimal("17")?,))), T6e6f6d696e616c28343a5472656529::V1(Box::new((T6e6f6d696e616c28343a5472656529::V0(Box::new((Nat::decimal("19")?,))), T6e6f6d696e616c28343a5472656529::V0(Box::new((Nat::decimal("23")?,))),))),))))
}

fn f_74726565546f74616c() -> Result<Nat, Error> {
    f_73756d54726565(Arc::new(f_74726565()?))
}

fn f_7472656553636f7265(a0: Arc<T6e6f6d696e616c28343a5472656529>) -> Result<Nat, Error> {
    Ok(match (*(Arc::clone(&(a0)))).clone() { T6e6f6d696e616c28343a5472656529::V0(payload1) => (*({ let (v1,) = *payload1; let v1 = Arc::new(v1); Arc::clone(&(v1)) })).clone(), T6e6f6d696e616c28343a5472656529::V1(payload1) => { let (v1, v2,) = *payload1; let v1 = Arc::new(v1); let v2 = Arc::new(v2); ((Nat::decimal("10")?).mul(&(f_7472656553636f7265(Arc::clone(&(v1)))?))?).add(&(f_7472656553636f7265(Arc::clone(&(v2)))?))? } })
}

fn f_6f72646572656454726565() -> Result<Nat, Error> {
    f_7472656553636f7265(Arc::new(f_74726565()?))
}

fn f_6576656e53697a65(a0: Arc<T6e6f6d696e616c28343a4576656e29>) -> Result<Nat, Error> {
    Ok(match (*(Arc::clone(&(a0)))).clone() { T6e6f6d696e616c28343a4576656e29::V0 => { Nat::decimal("0")? }, T6e6f6d696e616c28343a4576656e29::V1(payload1) => { let (v1,) = *payload1; let v1 = Arc::new(v1); (Nat::decimal("1")?).add(&(f_6f646453697a65(Arc::clone(&(v1)))?))? } })
}

fn f_6f646453697a65(a0: Arc<T6e6f6d696e616c28333a4f646429>) -> Result<Nat, Error> {
    Ok(match (*(Arc::clone(&(a0)))).clone() { T6e6f6d696e616c28333a4f646429::V0(payload1) => { let (v1,) = *payload1; let v1 = Arc::new(v1); (Nat::decimal("1")?).add(&(f_6576656e53697a65(Arc::clone(&(v1)))?))? } })
}

fn f_6d757475616c546f74616c() -> Result<Nat, Error> {
    f_6576656e53697a65(Arc::new(T6e6f6d696e616c28343a4576656e29::V1(Box::new((T6e6f6d696e616c28333a4f646429::V0(Box::new((T6e6f6d696e616c28343a4576656e29::V1(Box::new((T6e6f6d696e616c28333a4f646429::V0(Box::new((T6e6f6d696e616c28343a4576656e29::V0,))),))),))),)))))
}

fn f_63617074757265642430(a0: Arc<T6e6f6d696e616c28343a4c69737429>, a1: Arc<Nat>) -> Result<Nat, Error> {
    ((*(Arc::clone(&(a1)))).clone()).add(&(f_73756d4c697374(Arc::clone(&(a0)))?))
}

fn f_6361707475726564() -> Result<Nat, Error> {
    Ok({ let v0 = Arc::new(f_73616d706c65()?); { let v1 = Arc::new(c_636170747572656424303a31(Arc::clone(&(v0)))); (((Arc::clone(&(v1))).call)(Arc::new(Nat::decimal("3")?))?).add(&(((Arc::clone(&(v1))).call)(Arc::new(Nat::decimal("5")?))?))? } })
}

fn f_6f776e6564(a0: T6e6f6d696e616c28343a4c69737429) -> Result<T6e6f6d696e616c28343a4c69737429, Error> {
    Ok(a0)
}

fn f_706169726564() -> Result<T70726f64756374286e6f6d696e616c28343a4c697374292c6e617429, Error> {
    Ok(T70726f64756374286e6f6d696e616c28343a4c697374292c6e617429 { f0: f_73616d706c65()?, f1: Nat::decimal("41")? })
}

fn f_7265706561746564() -> Result<Nat, Error> {
    Ok({ let v0 = Arc::new(f_73616d706c65()?); (f_73756d4c697374(Arc::clone(&(v0)))?).add(&(f_73756d4c697374(Arc::clone(&(v0)))?))? })
}

fn f_65787472616374(a0: Arc<T6e6f6d696e616c28363a45726173656429>) -> Result<Nat, Error> {
    Ok(match (*(Arc::clone(&(a0)))).clone() { T6e6f6d696e616c28363a45726173656429::V0(payload1) => (*({ let (v1,) = *payload1; let v1 = Arc::new(v1); Arc::clone(&(v1)) })).clone() })
}

fn f_657261736564546f74616c() -> Result<Nat, Error> {
    f_65787472616374(Arc::new(T6e6f6d696e616c28363a45726173656429::V0(Box::new((Nat::decimal("43")?,)))))
}

fn f_63686f6f736556616c7565(a0: Arc<T6e6f6d696e616c28363a43686f69636529>) -> Result<Nat, Error> {
    Ok(match (*(Arc::clone(&(a0)))).clone() { T6e6f6d696e616c28363a43686f69636529::V0(payload1) => (*({ let (v1,) = *payload1; let v1 = Arc::new(v1); Arc::clone(&(v1)) })).clone(), T6e6f6d696e616c28363a43686f69636529::V1(payload1) => { let (v1,) = *payload1; let v1 = Arc::new(v1); (Nat::decimal("3")?).mul(&((*(Arc::clone(&(v1)))).clone()))? } })
}

fn f_63686f696365() -> Result<T6e6f6d696e616c28363a43686f69636529, Error> {
    Ok(T6e6f6d696e616c28363a43686f69636529::V0(Box::new((Nat::decimal("47")?,))))
}

fn f_63686f696365546f74616c() -> Result<Nat, Error> {
    f_63686f6f736556616c7565(Arc::new(f_63686f696365()?))
}

fn f_6170706c7946756e6374696f6e73(a0: Arc<T6e6f6d696e616c28393a46756e6374696f6e7329>) -> Result<Nat, Error> {
    Ok(match (*(Arc::clone(&(a0)))).clone() { T6e6f6d696e616c28393a46756e6374696f6e7329::V0 => { Nat::decimal("0")? }, T6e6f6d696e616c28393a46756e6374696f6e7329::V1(payload1) => { let (v1, v2,) = *payload1; let v1 = Arc::new(v1); let v2 = Arc::new(v2); (((Arc::clone(&(v1))).call)(Arc::new(Nat::decimal("5")?))?).add(&(f_6170706c7946756e6374696f6e73(Arc::clone(&(v2)))?))? } })
}

fn f_66756e6374696f6e732430(a0: Arc<Nat>) -> Result<Nat, Error> {
    ((*(Arc::clone(&(a0)))).clone()).add(&(Nat::decimal("7")?))
}

fn f_66756e6374696f6e73() -> Result<T6e6f6d696e616c28393a46756e6374696f6e7329, Error> {
    Ok(T6e6f6d696e616c28393a46756e6374696f6e7329::V1(Box::new((c_66756e6374696f6e7324303a31(), T6e6f6d696e616c28393a46756e6374696f6e7329::V0,))))
}

fn f_66756e6374696f6e546f74616c() -> Result<Nat, Error> {
    f_6170706c7946756e6374696f6e73(Arc::new(f_66756e6374696f6e73()?))
}

fn f_756e77726170546f74616c(a0: Arc<T6e6f6d696e616c28373a5772617070656429>) -> Result<Nat, Error> {
    Ok(match (*(Arc::clone(&(a0)))).clone() { T6e6f6d696e616c28373a5772617070656429::V0(payload1) => { let (v1,) = *payload1; let v1 = Arc::new(v1); (f_73756d4c697374(Arc::new({ let T70726f64756374286e6f6d696e616c28343a4c697374292c6e617429 { f0: p0, f1: p1 } = (*(Arc::clone(&(v1)))).clone(); p0 }))?).add(&({ let T70726f64756374286e6f6d696e616c28343a4c697374292c6e617429 { f0: p0, f1: p1 } = (*(Arc::clone(&(v1)))).clone(); p1 }))? } })
}

fn f_77726170706564546f74616c() -> Result<Nat, Error> {
    f_756e77726170546f74616c(Arc::new(T6e6f6d696e616c28373a5772617070656429::V0(Box::new((f_706169726564()?,)))))
}
