// Generated by lanyard's native Rust printer.
use std::sync::Arc;

#[derive(Clone, Debug, PartialEq, Eq)]
struct Nat(Vec<u8>);

#[derive(Debug)]
enum Error { Digit, Arithmetic }
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Digit => f.write_str("invalid natural digit"),
            Self::Arithmetic => f.write_str("natural limb invariant failed"),
        }
    }
}
impl std::error::Error for Error {}

impl Nat {
    fn canonical(bytes: Vec<u8>) -> Self {
        Self(bytes.into_iter().rev().skip_while(|b| *b == 0).collect::<Vec<_>>()
            .into_iter().rev().collect())
    }
    fn decimal(text: &str) -> Result<Self, Error> {
        text.bytes().try_fold(Self(Vec::new()), |n, c| {
            if c.is_ascii_digit() {
                n.scale(10)?.add(&Self::canonical(vec![c - b'0']))
            } else { Err(Error::Digit) }
        })
    }
    fn compare(&self, other: &Self) -> std::cmp::Ordering {
        self.0.len().cmp(&other.0.len()).then_with(|| self.0.iter().rev().cmp(other.0.iter().rev()))
    }
    fn finish(bytes: Vec<u8>, carry: u16) -> Result<Self, Error> {
        u8::try_from(carry).map_err(|_| Error::Arithmetic)
            .map(|last| Self::canonical(bytes.into_iter().chain(std::iter::once(last)).collect()))
    }
    fn add(&self, other: &Self) -> Result<Self, Error> {
        let (bytes, carry) = (0..self.0.len().max(other.0.len())).try_fold(
            (Vec::new(), 0_u16), |(bytes, carry), i| {
                let sum = self.0.get(i).map_or(0, |b| u16::from(*b))
                    + other.0.get(i).map_or(0, |b| u16::from(*b)) + carry;
                u8::try_from(sum % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), sum / 256))
            })?;
        Self::finish(bytes, carry)
    }
    fn sub(&self, other: &Self) -> Result<Self, Error> {
        if self.compare(other).is_lt() { Ok(Self(Vec::new())) } else {
        let (bytes, borrow) = self.0.iter().enumerate().try_fold(
            (Vec::new(), 0_u16), |(bytes, borrow), (i, byte)| {
                let rhs = other.0.get(i).map_or(0, |b| u16::from(*b)) + borrow;
                let lhs = u16::from(*byte);
                u8::try_from((lhs + 256 - rhs) % 256).map_err(|_| Error::Arithmetic)
                    .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), u16::from(lhs < rhs)))
            })?;
        if borrow == 0 { Ok(Self::canonical(bytes)) } else { Err(Error::Arithmetic) }
        }
    }
    fn scale(&self, factor: u8) -> Result<Self, Error> {
        let (bytes, carry) = self.0.iter().try_fold((Vec::new(), 0_u16), |(bytes, carry), byte| {
            let product = u16::from(*byte) * u16::from(factor) + carry;
            u8::try_from(product % 256).map_err(|_| Error::Arithmetic)
                .map(|byte| (bytes.into_iter().chain(std::iter::once(byte)).collect(), product / 256))
        })?;
        Self::finish(bytes, carry)
    }
    fn mul(&self, other: &Self) -> Result<Self, Error> {
        other.0.iter().enumerate().try_fold(Self(Vec::new()), |sum, (i, byte)| {
            let scaled = self.scale(*byte)?;
            let shifted = Self::canonical(std::iter::repeat_n(0, i).chain(scaled.0).collect());
            sum.add(&shifted)
        })
    }
}

struct T636c6f7375726528736861726564286e6174293b6e617429 {
    call: Box<dyn Fn(Arc<Nat>) -> Result<Nat, Error> + Send + Sync>,
    duplicate: Box<dyn Fn() -> Self + Send + Sync>,
}
impl Clone for T636c6f7375726528736861726564286e6174293b6e617429 {
    fn clone(&self) -> Self { (self.duplicate)() }
}
impl std::fmt::Debug for T636c6f7375726528736861726564286e6174293b6e617429 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str("Closure") }
}

#[derive(Clone, Debug)]
struct T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929 { f0: T636c6f7375726528736861726564286e6174293b6e617429 }

#[derive(Clone, Debug, PartialEq, Eq)]
enum T73756d28756e69742c756e697429 { V0(()), V1(()) }

fn c_7061636b24303a31(c0: Arc<Nat>) -> T636c6f7375726528736861726564286e6174293b6e617429 {
    let saved_c0 = Arc::clone(&(c0));
    T636c6f7375726528736861726564286e6174293b6e617429 {
        call: Box::new(move |p0: Arc<Nat>| f_7061636b2430(Arc::clone(&(c0)), p0)),
        duplicate: Box::new(move || c_7061636b24303a31(Arc::clone(&(saved_c0)))),
    }
}

fn f_6f6666736574() -> Result<Nat, Error> {
    Nat::decimal("7")
}

fn f_7061636b2430(a0: Arc<Nat>, a1: Arc<Nat>) -> Result<Nat, Error> {
    (((*(Arc::clone(&(a0)))).clone()).add(&((*(Arc::clone(&(a1)))).clone()))?).add(&(f_6f6666736574()?))
}

fn f_7061636b(a0: Arc<Nat>) -> Result<T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929, Error> {
    Ok(T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929 { f0: c_7061636b24303a31(Arc::clone(&(a0))) })
}

fn f_696e766f6b65(a0: Arc<T636c6f7375726528736861726564286e6174293b6e617429>) -> Result<Nat, Error> {
    ((Arc::clone(&(a0))).call)(Arc::new(Nat::decimal("11")?))
}

fn f_73656c6563746564() -> Result<Nat, Error> {
    f_696e766f6b65(Arc::new({ let T70726f6475637428636c6f7375726528736861726564286e6174293b6e61742929 { f0: p0 } = f_7061636b(Arc::new(Nat::decimal("13")?))?; p0 }))
}

fn f_6d61696e() -> Result<Nat, Error> {
    f_73656c6563746564()
}

fn main() -> Result<(), Error> {
    f_6d61696e()?;
    Ok(())
}
